# Site settings
title: My new world
description: My new world
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cemsinano.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cem Sinan Ozturk
user_description: Master of Data Science Student at UBC
user_title: Master of Data Science Student at UBC
email: cemsinanozturk@gmail.com
twitter_username: cmsnnztrk
github_username: cemsinano
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
